services:
  backend:
    build:
      context: ./backend
    ports:
      - "${BACKEND_PORT}:8089"
    environment:
      - FLASK_ENV=development
      - BACKEND_PORT=${BACKEND_PORT}
      - GEMINI_API_KEY=${GEMINI_API_KEY}
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    tty: true

  frontend:
    build:
      context: ./frontend
    ports:
      - "${FRONTEND_PORT}:3000"
    environment:
      - NODE_ENV=production
      - FRONTEND_PORT=${FRONTEND_PORT}
    depends_on:
      - backend
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    tty: true
